// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiuQTwMUfk-rpgp3I6GZ2-AZ6viNjaZq0',
    appId: '1:50258061076:web:b579cbc8f03236be648401',
    messagingSenderId: '50258061076',
    projectId: 'taskazurah',
    authDomain: 'taskazurah.firebaseapp.com',
    storageBucket: 'taskazurah.firebasestorage.app',
    measurementId: 'G-YRMKREZXRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD84FOaSO-9UDDOpN452qIgROtMpaoz6SI',
    appId: '1:50258061076:android:5b72fc193b032d2e648401',
    messagingSenderId: '50258061076',
    projectId: 'taskazurah',
    storageBucket: 'taskazurah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOVoiS3PyoKzotjZbqwpkaL86izw0m4_s',
    appId: '1:50258061076:ios:2849dd8f5fa6e287648401',
    messagingSenderId: '50258061076',
    projectId: 'taskazurah',
    storageBucket: 'taskazurah.firebasestorage.app',
    iosBundleId: 'com.example.parentAppFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOVoiS3PyoKzotjZbqwpkaL86izw0m4_s',
    appId: '1:50258061076:ios:2849dd8f5fa6e287648401',
    messagingSenderId: '50258061076',
    projectId: 'taskazurah',
    storageBucket: 'taskazurah.firebasestorage.app',
    iosBundleId: 'com.example.parentAppFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiuQTwMUfk-rpgp3I6GZ2-AZ6viNjaZq0',
    appId: '1:50258061076:web:c3ae922374b4f359648401',
    messagingSenderId: '50258061076',
    projectId: 'taskazurah',
    authDomain: 'taskazurah.firebaseapp.com',
    storageBucket: 'taskazurah.firebasestorage.app',
    measurementId: 'G-2NMDCNPLJ9',
  );

}